const zonesByExpansion = {
  arr: [
    'Middle La Noscea',
    'Lower La Noscea',
    'Eastern La Noscea',
    'Western La Noscea',
    'Upper La Noscea',
    'Outer La Noscea',
    'Western Thanalan',
    'Central Thanalan',
    'Eastern Thanalan',
    'Southern Thanalan',
    'Northern Thanalan',
    'Central Shroud',
    'East Shroud',
    'North Shroud',
    'South Shroud',
    'Coerthas Central Highlands',
    'Mor Dhona',
    'Limsa Lominsa Upper Decks',
    'Limsa Lominsa Lower Decks',
    'New Gridania',
    'Old Gridania',
    "Ul'dah - Steps of Nald",
    "Ul'dah - Steps of Thal",
    'The Mists',
    'The Lavender Beds',
    'The Goblet',
    "Wolves' Den Pier",
  ],
  hw: [
    'Coerthas Western Highlands',
    'The Sea of Clouds',
    'The Dravanian Forelands',
    'The Churning Mists',
    'The Dravanian Hinterlands',
    'Azys Lla',
    'The Foundation',
    'The Pillars',
    'Idyllshire',
  ],
  sb: [
    'The Fringes',
    'The Peaks',
    'The Ruby Sea',
    'Yanxia',
    'The Azim Steppe',
    'The Lochs',
    'Lochs',
    "Rhalgr's Reach",
    'Kugane',
    'The Doman Enclave',
    'Shirogane',
  ],
  shb: [
    'Lakeland',
    'Kholusia',
    'Amh Araeng',
    'Il Mheg',
    "The Rak'tika Greatwood",
    'The Tempest',
    'Eulmore',
    'The Crystarium',
    'Lyhe Mheg',
  ],
  ew: [
    'Labyrinthos',
    'Thavnair',
    'Garlemald',
    'Mare Lamentorum',
    'Elpis',
    'Ultima Thule',
    'Radz-at-Han',
    'Old Sharlayan',
  ],
  dt: [
    'Urqopacha',
    "Kozama'uka",
    "Yak T'el",
    'Shaaloani',
    'Heritage Found',
    'Living Memory',
    'Solution Nine',
    'Tuliyollal',
  ],
};

const zones = Object.entries(zonesByExpansion).flatMap((entry) => entry[1]);

export { zones, zonesByExpansion };
